# OpenFactory configuration

# ---------------------------------------------------------------------------
# General configurations

# OpenFactory Version
# This value is injected automatically by OpenFactory at runtime.
# DO NOT set OPENFACTORY_VERSION manually.
OPENFACTORY_VERSION: ${OPENFACTORY_VERSION}

# OpenFactory Log Level
OPENFACTORY_LOG_LEVEL: INFO
KSQLDB_LOG_LEVEL: WARNING
KAFKA_LOG_LEVEL: WARNING

# OpenFactory UNS definiton
OPENFACTORY_UNS_SCHEMA: ${OPENFACTORY_UNS_SCHEMA}

# ---------------------------------------------------------------------------
# OpenFactory cluster configurations

# Deployment platform
DEPLOYMENT_PLATFORM: ${DEPLOYMENT_PLATFORM:-swarm}

# OpenFactory User
OPENFACTORY_USER: openfactory

# OpenFactory Manager Node Docker URL

# Use Docker running on the host via Unix socket
OPENFACTORY_MANAGER_NODE_DOCKER_URL: unix:///var/run/docker.sock

# Alternatively, connect to Docker on a remote machine via SSH
# OPENFACTORY_MANAGER_NODE_DOCKER_URL: ssh://${OPENFACTORY_USER}@${MANAGER_NODE_IP}

# OpenFactory Overlay network
OPENFACTORY_NETWORK: factory-net

# Traefik configurations
OPENFACTORY_DOMAIN: ${OPENFACTORY_DOMAIN}

# ---------------------------------------------------------------------------
# Kafka related configurations

# Kafka-Cluster
# Comma-separated list of broker addresses (hostnames or IPs) with ports
# Example: 123.456.67.8:9092,123.456.67.9:9092,broker3.example.com:9092
KAFKA_BROKER: ${KAFKA_BROKER}

# ksqlDB server URL
KSQLDB_URL: ${KSQLDB_URL}

# ---------------------------------------------------------------------------
# Docker Images

MTCONNECT_AGENT_IMAGE: ghcr.io/openfactoryio/mtcagent:v2.5.0.11
MTCONNECT_PRODUCER_IMAGE: ghcr.io/openfactoryio/kafka-mtc-producer:${OPENFACTORY_VERSION}

# Colors for ofa cli
OFA_SUCCSESS: "\e[0;32m"   # Green for success
OFA_FAIL: "\e[0;31m"       # Red for failure
OFA_WARNING: "\e[0;33m"    # Yellow for warning
OFA_END: "\e[0m"           # Reset color
