"""
Generate a coverage badge (SVG) from a pytest/coverage.py XML report.

This script reads the 'coverage.xml' file generated by pytest with the
--cov-report=xml option, calculates the line coverage percentage, and
produces a simple SVG badge that can be embedded in the repository
(e.g., README.md) or committed back to the repo.

The badge color indicates coverage level:
    - Green (#4c1) for coverage >= 90%
    - Yellow (#dfb317) for coverage >= 70%
    - Red (#e05d44) for coverage < 70%

Usage:
    python scripts/coverage_badge.py

Output:
    - tests/coverage.svg : the generated badge SVG file
"""
import xml.etree.ElementTree as ET

tree = ET.parse("coverage.xml")
root = tree.getroot()
coverage_percent = float(root.attrib.get("line-rate", 0)) * 100

color = "#4c1" if coverage_percent >= 90 else "#dfb317" if coverage_percent >= 70 else "#e05d44"

svg = f'''<svg xmlns="http://www.w3.org/2000/svg" width="120" height="20">
  <rect width="70" height="20" fill="#555"/>
  <rect x="70" width="50" height="20" fill="{color}"/>
  <text x="35" y="14" fill="#fff" font-family="Verdana" font-size="11" text-anchor="middle">coverage</text>
  <text x="95" y="14" fill="#fff" font-family="Verdana" font-size="11" text-anchor="middle">{int(coverage_percent)}%</text>
</svg>'''

with open("tests/coverage.svg", "w") as f:
    f.write(svg)