name: PR Checks

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    name: Run Linter
    uses: ./.github/workflows/lint.yml

  unit-tests:
    name: Run Unit Tests
    uses: ./.github/workflows/unittests.yml

  test-coverage:
    name: Run test coverage calculation
    permissions:
      contents: write
    uses: ./.github/workflows/test_coverage.yml
